import {
  Camera,
  Music,
  Gamepad2,
  Dumbbell,
  Code,
  Palette,
  Film,
  Brain,
  Rocket,
  PenTool,
  BookOpenCheck,
  Mic2,
  MessageCircle,
  Globe,
  Coffee,
  Mountain,
  BookOpen,
  Heart,
  Trophy,
  Zap,
  FlaskConical,
  Sparkles,
  Lightbulb,
  Target,
  Shield,
  Sprout,
  Video,
  Briefcase,
  Gavel,
  Users,
  Cpu,
  MonitorSmartphone
} from "lucide-react";

export const INTEREST_TAGS = [
  // Original Student Onboarding interests
  { tag: "Photography", icon: Camera },
  { tag: "Music", icon: Music },
  { tag: "Gaming", icon: Gamepad2 },
  { tag: "Fitness", icon: Dumbbell },
  { tag: "Coding", icon: Code },
  { tag: "Design", icon: Palette },
  { tag: "Film", icon: Film },
  { tag: "AI / ML", icon: Brain },
  { tag: "Startups", icon: Rocket },
  { tag: "Art", icon: PenTool },
  { tag: "Books", icon: BookOpenCheck },
  { tag: "Open Mic", icon: Mic2 },
  { tag: "Debate", icon: MessageCircle },
  { tag: "Travel", icon: Globe },
  { tag: "Cafe Hopping", icon: Coffee },
  { tag: "Hiking", icon: Mountain },
  { tag: "Poetry", icon: BookOpen },
  { tag: "Cooking", icon: Heart },
  { tag: "Chess", icon: Trophy },
  { tag: "Esports", icon: Zap },
  { tag: "Robotics", icon: Cpu },
  { tag: "Dance", icon: Sparkles },
  { tag: "Psychology", icon: Lightbulb },
  { tag: "Finance", icon: Target },

  // Additional domains
  { tag: "Hackathons", icon: Code },
  { tag: "Entrepreneurship", icon: Briefcase },
  { tag: "Cybersecurity", icon: Shield },
  { tag: "UI/UX Design", icon: MonitorSmartphone },
  { tag: "Environment", icon: Sprout },
  { tag: "Sustainability", icon: Sprout },
  { tag: "Videography", icon: Video },
  { tag: "Film Making", icon: Film },
  { tag: "Theatre", icon: Sparkles },
  { tag: "Public Speaking", icon: Users },
  { tag: "MUN", icon: Gavel },
];
